# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrnTListing',
            new_name='Listing',
        ),
        migrations.RenameModel(
            old_name='FrnTUser',
            new_name='User',
        ),
    ]
