# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161111_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='picture',
        ),
        migrations.AddField(
            model_name='listing',
            name='pictures',
            field=models.ManyToManyField(to='main.ListingPicture'),
        ),
    ]
