# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161116_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(),
        ),
    ]
